// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (profile_id, name, platform, handle, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, profile_id, name, platform, handle, description, created_at, updated_at
`

type CreateChannelParams struct {
	ProfileID   pgtype.UUID `json:"profile_id"`
	Name        string      `json:"name"`
	Platform    string      `json:"platform"`
	Handle      string      `json:"handle"`
	Description string      `json:"description"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ProfileID,
		arg.Name,
		arg.Platform,
		arg.Handle,
		arg.Description,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Platform,
		&i.Handle,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels
WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, profile_id, name, platform, handle, description, created_at, updated_at FROM channels
WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Platform,
		&i.Handle,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelsByProfile = `-- name: ListChannelsByProfile :many
SELECT id, profile_id, name, platform, handle, description, created_at, updated_at FROM channels
WHERE profile_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListChannelsByProfile(ctx context.Context, profileID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Platform,
			&i.Handle,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileExists = `-- name: ProfileExists :one
SELECT EXISTS (SELECT 1 FROM profiles WHERE id = $1)
`

func (q *Queries) ProfileExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, profileExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = $2,
    platform = $3,
    handle = $4,
    description = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, profile_id, name, platform, handle, description, created_at, updated_at
`

type UpdateChannelParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Platform    string      `json:"platform"`
	Handle      string      `json:"handle"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Platform,
		arg.Handle,
		arg.Description,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Platform,
		&i.Handle,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
