// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: generations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGeneration = `-- name: CreateGeneration :one
INSERT INTO generations (
    profile_id, prompt_template_id, input_prompt, output, status, error, provider, model
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, profile_id, prompt_template_id, input_prompt, output, status, error, provider, model, created_at
`

type CreateGenerationParams struct {
	ProfileID        pgtype.UUID `json:"profile_id"`
	PromptTemplateID pgtype.UUID `json:"prompt_template_id"`
	InputPrompt      string      `json:"input_prompt"`
	Output           string      `json:"output"`
	Status           string      `json:"status"`
	Error            string      `json:"error"`
	Provider         string      `json:"provider"`
	Model            string      `json:"model"`
}

func (q *Queries) CreateGeneration(ctx context.Context, arg CreateGenerationParams) (Generation, error) {
	row := q.db.QueryRow(ctx, createGeneration,
		arg.ProfileID,
		arg.PromptTemplateID,
		arg.InputPrompt,
		arg.Output,
		arg.Status,
		arg.Error,
		arg.Provider,
		arg.Model,
	)
	var i Generation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PromptTemplateID,
		&i.InputPrompt,
		&i.Output,
		&i.Status,
		&i.Error,
		&i.Provider,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGeneration = `-- name: DeleteGeneration :execrows
DELETE FROM generations
WHERE id = $1
`

func (q *Queries) DeleteGeneration(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGeneration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishGeneration = `-- name: FinishGeneration :exec
UPDATE generations
SET status = $2,
    output = $3,
    error = $4,
    provider = $5,
    model = $6
WHERE id = $1
`

type FinishGenerationParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Output   string      `json:"output"`
	Error    string      `json:"error"`
	Provider string      `json:"provider"`
	Model    string      `json:"model"`
}

func (q *Queries) FinishGeneration(ctx context.Context, arg FinishGenerationParams) error {
	_, err := q.db.Exec(ctx, finishGeneration,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.Provider,
		arg.Model,
	)
	return err
}

const getGeneration = `-- name: GetGeneration :one
SELECT g.id, g.profile_id, g.prompt_template_id, g.input_prompt, g.output, g.status, g.error, g.provider, g.model, g.created_at, pt.name AS template_name
FROM generations g
LEFT JOIN prompt_templates pt ON pt.id = g.prompt_template_id
WHERE g.id = $1
`

type GetGenerationRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	PromptTemplateID pgtype.UUID        `json:"prompt_template_id"`
	InputPrompt      string             `json:"input_prompt"`
	Output           string             `json:"output"`
	Status           string             `json:"status"`
	Error            string             `json:"error"`
	Provider         string             `json:"provider"`
	Model            string             `json:"model"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TemplateName     *string            `json:"template_name"`
}

func (q *Queries) GetGeneration(ctx context.Context, id pgtype.UUID) (GetGenerationRow, error) {
	row := q.db.QueryRow(ctx, getGeneration, id)
	var i GetGenerationRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.PromptTemplateID,
		&i.InputPrompt,
		&i.Output,
		&i.Status,
		&i.Error,
		&i.Provider,
		&i.Model,
		&i.CreatedAt,
		&i.TemplateName,
	)
	return i, err
}

const listGenerationsByProfile = `-- name: ListGenerationsByProfile :many
SELECT g.id, g.profile_id, g.prompt_template_id, g.input_prompt, g.output, g.status, g.error, g.provider, g.model, g.created_at, pt.name AS template_name
FROM generations g
LEFT JOIN prompt_templates pt ON pt.id = g.prompt_template_id
WHERE g.profile_id = $1
ORDER BY g.created_at DESC
`

type ListGenerationsByProfileRow struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	PromptTemplateID pgtype.UUID        `json:"prompt_template_id"`
	InputPrompt      string             `json:"input_prompt"`
	Output           string             `json:"output"`
	Status           string             `json:"status"`
	Error            string             `json:"error"`
	Provider         string             `json:"provider"`
	Model            string             `json:"model"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TemplateName     *string            `json:"template_name"`
}

func (q *Queries) ListGenerationsByProfile(ctx context.Context, profileID pgtype.UUID) ([]ListGenerationsByProfileRow, error) {
	rows, err := q.db.Query(ctx, listGenerationsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenerationsByProfileRow
	for rows.Next() {
		var i ListGenerationsByProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.PromptTemplateID,
			&i.InputPrompt,
			&i.Output,
			&i.Status,
			&i.Error,
			&i.Provider,
			&i.Model,
			&i.CreatedAt,
			&i.TemplateName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
