// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	Name        string             `json:"name"`
	Platform    string             `json:"platform"`
	Handle      string             `json:"handle"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Generation struct {
	ID               pgtype.UUID        `json:"id"`
	ProfileID        pgtype.UUID        `json:"profile_id"`
	PromptTemplateID pgtype.UUID        `json:"prompt_template_id"`
	InputPrompt      string             `json:"input_prompt"`
	Output           string             `json:"output"`
	Status           string             `json:"status"`
	Error            string             `json:"error"`
	Provider         string             `json:"provider"`
	Model            string             `json:"model"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Niche       string             `json:"niche"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PromptTemplate struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	Name        string             `json:"name"`
	Body        string             `json:"body"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	TokenHash []byte             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
