// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID          pgtype.UUID        `json:"id"`
	ProfileID   pgtype.UUID        `json:"profile_id"`
	Name        string             `json:"name"`
	Platform    string             `json:"platform"`
	Handle      string             `json:"handle"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Niche       string             `json:"niche"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	TokenHash []byte             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}
