// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (name, niche, description, provider)
VALUES ($1, $2, $3, $4)
RETURNING id, name, niche, description, provider, created_at, updated_at
`

type CreateProfileParams struct {
	Name        string `json:"name"`
	Niche       string `json:"niche"`
	Description string `json:"description"`
	Provider    string `json:"provider"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.Name,
		arg.Niche,
		arg.Description,
		arg.Provider,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Niche,
		&i.Description,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :execrows
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProfile = `-- name: GetProfile :one
SELECT id, name, niche, description, provider, created_at, updated_at FROM profiles
WHERE id = $1
`

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Niche,
		&i.Description,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, name, niche, description, provider, created_at, updated_at FROM profiles
ORDER BY created_at DESC
`

func (q *Queries) ListProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Niche,
			&i.Description,
			&i.Provider,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET name = $2,
    niche = $3,
    description = $4,
    provider = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, niche, description, provider, created_at, updated_at
`

type UpdateProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Niche       string      `json:"niche"`
	Description string      `json:"description"`
	Provider    string      `json:"provider"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Niche,
		arg.Description,
		arg.Provider,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Niche,
		&i.Description,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
