// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompt_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPromptTemplate = `-- name: CreatePromptTemplate :one
INSERT INTO prompt_templates (profile_id, name, body, description)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, name, body, description, created_at, updated_at
`

type CreatePromptTemplateParams struct {
	ProfileID   pgtype.UUID `json:"profile_id"`
	Name        string      `json:"name"`
	Body        string      `json:"body"`
	Description string      `json:"description"`
}

func (q *Queries) CreatePromptTemplate(ctx context.Context, arg CreatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, createPromptTemplate,
		arg.ProfileID,
		arg.Name,
		arg.Body,
		arg.Description,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Body,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePromptTemplate = `-- name: DeletePromptTemplate :execrows
DELETE FROM prompt_templates
WHERE id = $1
`

func (q *Queries) DeletePromptTemplate(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePromptTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, profile_id, name, body, description, created_at, updated_at FROM prompt_templates
WHERE id = $1
`

func (q *Queries) GetPromptTemplate(ctx context.Context, id pgtype.UUID) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, getPromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Body,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromptTemplatesByProfile = `-- name: ListPromptTemplatesByProfile :many
SELECT id, profile_id, name, body, description, created_at, updated_at FROM prompt_templates
WHERE profile_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPromptTemplatesByProfile(ctx context.Context, profileID pgtype.UUID) ([]PromptTemplate, error) {
	rows, err := q.db.Query(ctx, listPromptTemplatesByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptTemplate
	for rows.Next() {
		var i PromptTemplate
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Body,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromptTemplate = `-- name: UpdatePromptTemplate :one
UPDATE prompt_templates
SET name = $2,
    body = $3,
    description = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, profile_id, name, body, description, created_at, updated_at
`

type UpdatePromptTemplateParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Body        string      `json:"body"`
	Description string      `json:"description"`
}

func (q *Queries) UpdatePromptTemplate(ctx context.Context, arg UpdatePromptTemplateParams) (PromptTemplate, error) {
	row := q.db.QueryRow(ctx, updatePromptTemplate,
		arg.ID,
		arg.Name,
		arg.Body,
		arg.Description,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Body,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
