// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, expires_at)
VALUES ($1, $2)
`

type CreateSessionParams struct {
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token_hash, created_at, expires_at FROM sessions
WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, tokenHash)
	var i Session
	err := row.Scan(&i.TokenHash, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}
