// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: youtube_accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteYouTubeAccount = `-- name: DeleteYouTubeAccount :execrows
DELETE FROM youtube_accounts
WHERE channel_id = $1
`

func (q *Queries) DeleteYouTubeAccount(ctx context.Context, channelID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteYouTubeAccount, channelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getYouTubeAccount = `-- name: GetYouTubeAccount :one
SELECT channel_id, youtube_channel_id, youtube_title, access_token, refresh_token, token_expiry, scope, connected_at, updated_at FROM youtube_accounts
WHERE channel_id = $1
`

func (q *Queries) GetYouTubeAccount(ctx context.Context, channelID pgtype.UUID) (YoutubeAccount, error) {
	row := q.db.QueryRow(ctx, getYouTubeAccount, channelID)
	var i YoutubeAccount
	err := row.Scan(
		&i.ChannelID,
		&i.YoutubeChannelID,
		&i.YoutubeTitle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.Scope,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listYouTubeAccountsByProfile = `-- name: ListYouTubeAccountsByProfile :many
SELECT ya.channel_id, ya.youtube_channel_id, ya.youtube_title, ya.access_token, ya.refresh_token, ya.token_expiry, ya.scope, ya.connected_at, ya.updated_at FROM youtube_accounts ya
JOIN channels c ON c.id = ya.channel_id
WHERE c.profile_id = $1
`

func (q *Queries) ListYouTubeAccountsByProfile(ctx context.Context, profileID pgtype.UUID) ([]YoutubeAccount, error) {
	rows, err := q.db.Query(ctx, listYouTubeAccountsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YoutubeAccount
	for rows.Next() {
		var i YoutubeAccount
		if err := rows.Scan(
			&i.ChannelID,
			&i.YoutubeChannelID,
			&i.YoutubeTitle,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.Scope,
			&i.ConnectedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateYouTubeTokens = `-- name: UpdateYouTubeTokens :exec
UPDATE youtube_accounts
SET access_token = $2,
    token_expiry = $3,
    updated_at   = now()
WHERE channel_id = $1
`

type UpdateYouTubeTokensParams struct {
	ChannelID   pgtype.UUID        `json:"channel_id"`
	AccessToken string             `json:"access_token"`
	TokenExpiry pgtype.Timestamptz `json:"token_expiry"`
}

func (q *Queries) UpdateYouTubeTokens(ctx context.Context, arg UpdateYouTubeTokensParams) error {
	_, err := q.db.Exec(ctx, updateYouTubeTokens, arg.ChannelID, arg.AccessToken, arg.TokenExpiry)
	return err
}

const upsertYouTubeAccount = `-- name: UpsertYouTubeAccount :one
INSERT INTO youtube_accounts (
    channel_id, youtube_channel_id, youtube_title,
    access_token, refresh_token, token_expiry, scope, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (channel_id) DO UPDATE
SET youtube_channel_id = EXCLUDED.youtube_channel_id,
    youtube_title      = EXCLUDED.youtube_title,
    access_token       = EXCLUDED.access_token,
    -- Keep the stored refresh token if this exchange didn't return one.
    refresh_token      = COALESCE(NULLIF(EXCLUDED.refresh_token, ''), youtube_accounts.refresh_token),
    token_expiry       = EXCLUDED.token_expiry,
    scope              = EXCLUDED.scope,
    updated_at         = now()
RETURNING channel_id, youtube_channel_id, youtube_title, access_token, refresh_token, token_expiry, scope, connected_at, updated_at
`

type UpsertYouTubeAccountParams struct {
	ChannelID        pgtype.UUID        `json:"channel_id"`
	YoutubeChannelID string             `json:"youtube_channel_id"`
	YoutubeTitle     string             `json:"youtube_title"`
	AccessToken      string             `json:"access_token"`
	RefreshToken     string             `json:"refresh_token"`
	TokenExpiry      pgtype.Timestamptz `json:"token_expiry"`
	Scope            string             `json:"scope"`
}

func (q *Queries) UpsertYouTubeAccount(ctx context.Context, arg UpsertYouTubeAccountParams) (YoutubeAccount, error) {
	row := q.db.QueryRow(ctx, upsertYouTubeAccount,
		arg.ChannelID,
		arg.YoutubeChannelID,
		arg.YoutubeTitle,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.Scope,
	)
	var i YoutubeAccount
	err := row.Scan(
		&i.ChannelID,
		&i.YoutubeChannelID,
		&i.YoutubeTitle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.Scope,
		&i.ConnectedAt,
		&i.UpdatedAt,
	)
	return i, err
}
