// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: youtube_uploads.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createYouTubeUpload = `-- name: CreateYouTubeUpload :one
INSERT INTO youtube_uploads (generation_id, channel_id, youtube_video_id, privacy, title)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, generation_id, channel_id, youtube_video_id, privacy, title, created_at
`

type CreateYouTubeUploadParams struct {
	GenerationID   pgtype.UUID `json:"generation_id"`
	ChannelID      pgtype.UUID `json:"channel_id"`
	YoutubeVideoID string      `json:"youtube_video_id"`
	Privacy        string      `json:"privacy"`
	Title          string      `json:"title"`
}

func (q *Queries) CreateYouTubeUpload(ctx context.Context, arg CreateYouTubeUploadParams) (YoutubeUpload, error) {
	row := q.db.QueryRow(ctx, createYouTubeUpload,
		arg.GenerationID,
		arg.ChannelID,
		arg.YoutubeVideoID,
		arg.Privacy,
		arg.Title,
	)
	var i YoutubeUpload
	err := row.Scan(
		&i.ID,
		&i.GenerationID,
		&i.ChannelID,
		&i.YoutubeVideoID,
		&i.Privacy,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const listYouTubeUploadsByProfile = `-- name: ListYouTubeUploadsByProfile :many
SELECT yu.id, yu.generation_id, yu.channel_id, yu.youtube_video_id, yu.privacy, yu.title, yu.created_at FROM youtube_uploads yu
JOIN generations g ON g.id = yu.generation_id
WHERE g.profile_id = $1
ORDER BY yu.created_at DESC
`

func (q *Queries) ListYouTubeUploadsByProfile(ctx context.Context, profileID pgtype.UUID) ([]YoutubeUpload, error) {
	rows, err := q.db.Query(ctx, listYouTubeUploadsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YoutubeUpload
	for rows.Next() {
		var i YoutubeUpload
		if err := rows.Scan(
			&i.ID,
			&i.GenerationID,
			&i.ChannelID,
			&i.YoutubeVideoID,
			&i.Privacy,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
